name: example
description: "A set of example applications demonstrating the use of the base_menu package."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+3

environment:
  sdk: ^3.11.4
  flutter: ">=3.44.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  base_menu: 
    path: ../
  flutter:
    sdk: flutter
  vector_math: ^2.2.0
  material_symbols_icons: ^4.2928.1
  google_fonts: ^8.1.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Main
      fonts:
        - asset: assets/InterVariable_.ttf
    - family: InterVariable
      fonts:
        - asset: assets/InterVariable.ttf
    - family: RobotoFlex
      fonts:
        - asset: assets/Roboto.ttf
    - family: GoogleSans
      fonts:
        - asset: assets/GoogleSans.ttf
    - family: GoogleSansFlex
      fonts:
        - asset: assets/GoogleSansFlex.ttf
    - family: GoogleSansCode
      fonts:
        - asset: assets/GoogleSansCode.ttf
    - family: Amatic SC
      fonts:
        - asset: assets/Amatic_SC_400.ttf
    - family: Caveat
      fonts:
        - asset: assets/Caveat_400.ttf
        - asset: assets/Caveat_500.ttf
        - asset: assets/Caveat_600.ttf
        - asset: assets/Caveat_700.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/Comfortaa_300.ttf
        - asset: assets/Comfortaa_400.ttf
        - asset: assets/Comfortaa_700.ttf
    - family: EB Garamond
      fonts:
        - asset: assets/EB_Garamond_400.ttf
        - asset: assets/EB_Garamond_500.ttf
        - asset: assets/EB_Garamond_600.ttf
        - asset: assets/EB_Garamond_700.ttf
        - asset: assets/EB_Garamond_800.ttf
    - family: Inter
      fonts:
        - asset: assets/Inter_100.ttf
        - asset: assets/Inter_200.ttf
        - asset: assets/Inter_300.ttf
        - asset: assets/Inter_400.ttf
        - asset: assets/Inter_500.ttf
        - asset: assets/Inter_600.ttf
        - asset: assets/Inter_700.ttf
        - asset: assets/Inter_800.ttf
        - asset: assets/Inter_900.ttf
    - family: Lato
      fonts:
        - asset: assets/Lato_100.ttf
        - asset: assets/Lato_300.ttf
        - asset: assets/Lato_400.ttf
        - asset: assets/Lato_700.ttf
        - asset: assets/Lato_900.ttf
    - family: Lexend
      fonts:
        - asset: assets/Lexend_100.ttf
        - asset: assets/Lexend_200.ttf
        - asset: assets/Lexend_300.ttf
        - asset: assets/Lexend_400.ttf
        - asset: assets/Lexend_500.ttf
        - asset: assets/Lexend_600.ttf
        - asset: assets/Lexend_700.ttf
        - asset: assets/Lexend_800.ttf
        - asset: assets/Lexend_900.ttf
    - family: Libre Baskerville
      fonts:
        - asset: assets/Libre_Baskerville_400.ttf
        - asset: assets/Libre_Baskerville_700.ttf
    - family: Lora
      fonts:
        - asset: assets/Lora_400.ttf
        - asset: assets/Lora_500.ttf
        - asset: assets/Lora_600.ttf
        - asset: assets/Lora_700.ttf
    - family: Merriweather
      fonts:
        - asset: assets/Merriweather_300.ttf
        - asset: assets/Merriweather_400.ttf
        - asset: assets/Merriweather_700.ttf
        - asset: assets/Merriweather_900.ttf
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat_100.ttf
        - asset: assets/Montserrat_200.ttf
        - asset: assets/Montserrat_300.ttf
        - asset: assets/Montserrat_400.ttf
        - asset: assets/Montserrat_500.ttf
        - asset: assets/Montserrat_600.ttf
        - asset: assets/Montserrat_700.ttf
        - asset: assets/Montserrat_800.ttf
        - asset: assets/Montserrat_900.ttf
    - family: Nunito
      fonts:
        - asset: assets/Nunito_200.ttf
        - asset: assets/Nunito_300.ttf
        - asset: assets/Nunito_400.ttf
        - asset: assets/Nunito_500.ttf
        - asset: assets/Nunito_600.ttf
        - asset: assets/Nunito_700.ttf
        - asset: assets/Nunito_800.ttf
        - asset: assets/Nunito_900.ttf
    - family: Oswald
      fonts:
        - asset: assets/Oswald_200.ttf
        - asset: assets/Oswald_300.ttf
        - asset: assets/Oswald_400.ttf
        - asset: assets/Oswald_500.ttf
        - asset: assets/Oswald_600.ttf
        - asset: assets/Oswald_700.ttf
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico_400.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/Playfair_Display_400.ttf
        - asset: assets/Playfair_Display_500.ttf
        - asset: assets/Playfair_Display_600.ttf
        - asset: assets/Playfair_Display_700.ttf
        - asset: assets/Playfair_Display_800.ttf
        - asset: assets/Playfair_Display_900.ttf
    - family: Raleway
      fonts:
        - asset: assets/Raleway_100.ttf
        - asset: assets/Raleway_200.ttf
        - asset: assets/Raleway_300.ttf
        - asset: assets/Raleway_400.ttf
        - asset: assets/Raleway_500.ttf
        - asset: assets/Raleway_600.ttf
        - asset: assets/Raleway_700.ttf
        - asset: assets/Raleway_800.ttf
        - asset: assets/Raleway_900.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto_100.ttf
        - asset: assets/Roboto_300.ttf
        - asset: assets/Roboto_400.ttf
        - asset: assets/Roboto_500.ttf
        - asset: assets/Roboto_700.ttf
        - asset: assets/Roboto_900.ttf
    - family: Roboto Mono
      fonts:
        - asset: assets/Roboto_Mono_100.ttf
        - asset: assets/Roboto_Mono_300.ttf
        - asset: assets/Roboto_Mono_400.ttf
        - asset: assets/Roboto_Mono_500.ttf
        - asset: assets/Roboto_Mono_700.ttf
    - family: Roboto Serif
      fonts:
        - asset: assets/Roboto_Serif_100.ttf
        - asset: assets/Roboto_Serif_200.ttf
        - asset: assets/Roboto_Serif_300.ttf
        - asset: assets/Roboto_Serif_400.ttf
        - asset: assets/Roboto_Serif_500.ttf
        - asset: assets/Roboto_Serif_600.ttf
        - asset: assets/Roboto_Serif_700.ttf
        - asset: assets/Roboto_Serif_800.ttf
        - asset: assets/Roboto_Serif_900.ttf
    - family: Roboto Slab
      fonts:
        - asset: assets/Roboto_Slab_100.ttf
        - asset: assets/Roboto_Slab_200.ttf
        - asset: assets/Roboto_Slab_300.ttf
        - asset: assets/Roboto_Slab_400.ttf
        - asset: assets/Roboto_Slab_500.ttf
        - asset: assets/Roboto_Slab_600.ttf
        - asset: assets/Roboto_Slab_700.ttf
        - asset: assets/Roboto_Slab_800.ttf
        - asset: assets/Roboto_Slab_900.ttf
    - family: Source Sans 3
      fonts:
        - asset: assets/Source_Sans_3_200.ttf
        - asset: assets/Source_Sans_3_300.ttf
        - asset: assets/Source_Sans_3_400.ttf
        - asset: assets/Source_Sans_3_600.ttf
        - asset: assets/Source_Sans_3_700.ttf
        - asset: assets/Source_Sans_3_900.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/Ubuntu_300.ttf
        - asset: assets/Ubuntu_400.ttf
        - asset: assets/Ubuntu_500.ttf
        - asset: assets/Ubuntu_700.ttf
