name: base_menu_example
description: "Demonstrates how to use the base_menu package."
resolution: workspace
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.11.4

dependencies:
  base_menu:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

