name: base_menu
description: "Composable widgets for building menu systems."
version: 0.1.1
homepage: https://base-menu-library.web.app/
repository: https://github.com/davidhicks980/base_menu/tree/main 
issue_tracker: https://github.com/davidhicks980/base_menu/issues

topics:
  - menus
  - ui
workspace:
  - gallery
  - deployments/base_menu
  - deployments/floogle_docs
  - example

environment:
  sdk: ^3.11.4
  flutter: ">=3.44.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
    

false_secrets:
 - /deployments/base_menu/lib/firebase_options.dart
 - /deployments/floogle_docs/lib/firebase_options.dart
