name: base_menu
description: "Composable primitives for building accessible menu systems."
version: 0.2.0
homepage: https://base-menu-library.web.app/
repository: https://github.com/davidhicks980/base_menu/tree/main 
issue_tracker: https://github.com/davidhicks980/base_menu/issues
resolution: workspace

environment:
  sdk: ^3.11.4
  flutter: ">=3.44.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter